const projectDetails = [
    {
        projectID: 1,
        projectName: "Niwahana LK",
        projectSkills: ["HTML", "CSS", "JavaScript", "PHP", "MySQL"],
        projectDescription: "Niwahana LK is a web application for place house selling advertisements",
        projectURL: "https://github.com/DushanSenadheera/NiwahanaLK",
    },
    {
        projectID: 2,
        projectName: "Library Management System",
        projectSkills: ["C#", ".NET", "Windows Forms", "SQL Server"],
        projectDescription: "Desktop application to manage library tasks",
        projectURL: "https://github.com/DushanSenadheera/Library_Management_System",
    },
    {
        projectID: 3,
        projectName: "ABC Cinema",
        projectSkills: ["Java", "JSP", "Servlet", "MySQL"],
        projectDescription: "web application for cinema ticket booking system",
        projectURL: "https://via.placeholder.com/150",
    },
    {
        projectID: 4,
        projectName: "Companion",
        projectSkills: ["Flutter", "NodeJS", "ExpressJS", "MongoDB"],
        projectDescription: "social media like mobile application for charity",
        projectURL: "https://via.placeholder.com/150",
    },
    {
        projectID: 5,
        projectName: "Learning Management System",
        projectSkills: ["Flutter", "PHP", "MySQL"],
        projectDescription: "mobile application for learning management system",
        projectURL: "https://via.placeholder.com/150",
    },
    {
        projectID: 6,
        projectName: "React Component Generator",
        projectSkills: ["NodeJS", "NPM"],
        projectDescription: "This is a project description",
        projectURL: "https://via.placeholder.com/150",
    },
    {
        projectID: 7,
        projectName: "Context-aware Recommendation System",
        projectSkills: ["React", "NodeJS", "ExpressJS", "AWS", "Python"],
        projectDescription: "This is a project description",
        projectURL: "https://via.placeholder.com/150",
    },
    {
        projectID: 8,
        projectName: "AIDA website",
        projectSkills: ["React", "Mantine UI"],
        projectDescription: "This is a project description",
        projectURL: "https://via.placeholder.com/150",
    },
    {
        projectID: 9,
        projectName: "Job Portal App",
        projectSkills: ["React Native"],
        projectDescription: "This is a project description",
        projectURL: "https://via.placeholder.com/150",
    },
    {
        projectID: 10,
        projectName: "Movie Recommendation System",
        projectSkills: ["Python"],
        projectDescription: "This is a project description",
        projectURL: "https://via.placeholder.com/150",
    },
    {
        projectID: 11,
        projectName: "Port Scanner",
        projectSkills: ["Python", "nmap"],
        projectDescription: "This is a project description",
        projectURL: "https://via.placeholder.com/150",
    },
    {
        projectID: 12,
        projectName: "GitHub Command Automation",
        projectSkills: ["Shell"],
        projectDescription: "This is a project description",
        projectURL: "https://via.placeholder.com/150",
    },
    {
        projectID: 13,
        projectName: "Automated hydrophonic greenhosue",
        projectSkills: ["Arduino", "C++", "PHP", "MySQL"],
        projectDescription: "This is a project description",
        projectURL: "https://via.placeholder.com/150",
    },
]

export default projectDetails;