const projectDetails = [
    {
        projectID: 7,
        projectName: "MASS Group Website",
        projectSkills: ["NextJS", "TypeScript", "TailWind", "Aceternity UI", "i18next", "AWS"],
        projectDescription: "Company portfolio to showcase their services and details",
        projectURL: "https://via.placeholder.com/150",
    },
    {
        projectID: 7,
        projectName: "Aurora Grande Hotel Web Application",
        projectSkills: ["React", "Node", "Express", "MongoDB", "SCSS", "Material UI", "Styled Components", "JWT", "PayPal API", "Nodemailer"],
        projectDescription: "Hotel web application to showcase hotel information with admin dashboard to manage hotel reservations",
        projectURL: "https://via.placeholder.com/150",
    },
    {
        projectID: 7,
        projectName: "Context-aware Recommendation System",
        projectSkills: ["React", "SCSS", "Mantine UI", "NodeJS", "ExpressJS","GitHub Actions", "AWS", "Python", "Scikit Learn"],
        projectDescription: "Travel recommendation system that can use as a SaaS API for other applications",
        projectURL: "https://via.placeholder.com/150",
    },
    {
        projectID: 7,
        projectName: "React component generator",
        projectSkills: ["NodeJS", "NPM", "NPM Package", "React"],
        projectDescription: "NPX package to generate React components with a single command",
        projectURL: "https://via.placeholder.com/150",
    },
    {
        projectID: 7,
        projectName: "Nightfall Dev",
        projectSkills: ["JSON", "extension", "VS Code"],
        projectDescription: "VS Code extension for dark theme lovers",
        projectURL: "https://via.placeholder.com/150",
    },
    {
        projectID: 1,
        projectName: "Niwahana LK",
        projectSkills: ["HTML", "CSS", "JavaScript", "PHP", "MySQL", "Google Maps API"],
        projectDescription: "Web application for Green Task Force to locate and clear garbage collection around the city",
        projectURL: "https://github.com/DushanSenadheera/NiwahanaLK",
    },
    {
        projectID: 1,
        projectName: "Green City",
        projectSkills: ["HTML", "CSS", "JavaScript", "PHP", "MySQL"],
        projectDescription: "Niwahana LK is a web application for place house selling advertisements",
        projectURL: "https://github.com/DushanSenadheera/NiwahanaLK",
    },
    {
        projectID: 2,
        projectName: "Library Management System",
        projectSkills: ["C#", ".NET", "Windows Forms", "SQL Server"],
        projectDescription: "Desktop application to manage library tasks",
        projectURL: "https://github.com/DushanSenadheera/Library_Management_System",
    },
    {
        projectID: 3,
        projectName: "ABC Cinema",
        projectSkills: ["Java", "JSP", "Servlet", "MySQL"],
        projectDescription: "web application for cinema ticket booking system",
        projectURL: "https://via.placeholder.com/150",
    },
    {
        projectID: 4,
        projectName: "Companion",
        projectSkills: ["Flutter", "NodeJS", "ExpressJS", "MongoDB"],
        projectDescription: "social media like mobile application for charity, volunteering and fundraising",
        projectURL: "https://via.placeholder.com/150",
    },
    {
        projectID: 5,
        projectName: "Learning Management System",
        projectSkills: ["Flutter", "PHP", "MySQL"],
        projectDescription: "mobile application for learning management system",
        projectURL: "https://via.placeholder.com/150",
    },
    {
        projectID: 8,
        projectName: "AIDA website",
        projectSkills: ["React", "Mantine UI"],
        projectDescription: "japanese language institute website",
        projectURL: "https://via.placeholder.com/150",
    },
    {
        projectID: 9,
        projectName: "Job Portal App",
        projectSkills: ["React Native"],
        projectDescription: "mobile application for job portal",
        projectURL: "https://via.placeholder.com/150",
    },
    {
        projectID: 10,
        projectName: "Movie Recommendation System",
        projectSkills: ["Python"],
        projectDescription: "movie recommendation engine using content-based filtering algorithm",
        projectURL: "https://via.placeholder.com/150",
    },
    {
        projectID: 11,
        projectName: "Port Scanner",
        projectSkills: ["Python", "nmap"],
        projectDescription: "network port scanner using nmap library",
        projectURL: "https://via.placeholder.com/150",
    },
    {
        projectID: 12,
        projectName: "GitHub Command Automation",
        projectSkills: ["Shell"],
        projectDescription: "shell script to automate GitHub commands",
        projectURL: "https://via.placeholder.com/150",
    },
    {
        projectID: 13,
        projectName: "Automated hydrophonic greenhosue",
        projectSkills: ["Arduino", "C++", "PHP", "MySQL"],
        projectDescription: "automated hydrophonic greenhouse system using Arduino and PHP",
        projectURL: "https://via.placeholder.com/150",
    },
]

export default projectDetails;