import Marquee from "react-fast-marquee";
import "./Tech.scss";

export default function Tech() {
  return (
    <div className="tech">
        <h3 className="sub-heading">Tools & Technologies</h3>
      <Marquee>
      <img
          src="https://img.icons8.com/?size=48&id=Pd2x9GWu9ovX&format=png&color=000000"
          alt="Java"
        />
        <img
          src="https://img.icons8.com/color/48/000000/my-sql.png"
          alt="MySQL"
        />
        <img
          src="https://img.icons8.com/?size=48&id=fAMVO_fuoOuC&format=png&color=000000"
          alt="PHP"
        />
        <img
          src="https://img.icons8.com/color/48/000000/python--v1.png"
          alt="python"
        />
        <img
          src="https://img.icons8.com/color/48/000000/javascript--v1.png"
          alt="javascript"
        />
        <img
          src="https://img.icons8.com/color/48/000000/typescript.png"
          alt="typescript"
        />
        <img
          src="https://img.icons8.com/color/48/000000/react-native.png"
          alt="react"
        />
        <img
          src="https://img.icons8.com/color/48/000000/redux.png"
          alt="redux"
        />
        <img
          src="https://img.icons8.com/?size=48&id=yUdJlcKanVbh&format=png&color=000000"
          alt="nextjs"
        />
        <img
          src="https://img.icons8.com/color/48/000000/nodejs.png"
          alt="nodejs"
        />
        <img
          src="https://img.icons8.com/color/48/000000/mongodb.png"
          alt="mongodb"
        />
        <img
          src="https://img.icons8.com/color/48/000000/express-js.png"
          alt="express"
        />
        <img
          src="https://img.icons8.com/?size=48&id=bp24DwGXJDyT&format=png&color=000000"
          alt="jest"
        />
        <img
          src="https://img.icons8.com/color/48/000000/docker.png"
          alt="docker"
        />
        <img
          src="https://img.icons8.com/color/48/000000/kubernetes.png"
          alt="kubernetes"
        />
        <img
          src="https://img.icons8.com/color/48/000000/linux.png"
          alt="linux"
        />
        <img
          src="https://img.icons8.com/color/48/000000/amazon-web-services.png"
          alt="aws"
        />
        <img
          src="https://img.icons8.com/color/48/000000/bash.png"
          alt="bash"
        />
        <img
          src="https://img.icons8.com/color/48/000000/c-programming.png"
          alt="c"
        />
        <img
          src="https://img.icons8.com/color/48/000000/c-sharp-logo.png"
          alt="csharp"
        />
        <img
          src="https://img.icons8.com/color/48/000000/git.png"
          alt="git"
        />
        <img
          src="https://img.icons8.com/color/48/000000/arduino.png"
          alt="arduino"
        />
        <img
          src="https://img.icons8.com/color/48/000000/firebase.png"
          alt="firebase"
        />
        <img
          src="https://img.icons8.com/color/48/000000/sass.png"
            alt="sass"
        />
        <img
          src=" https://img.icons8.com/?size=48&id=4PiNHtUJVbLs&format=png&color=000000"
            alt="tailwindcss"
        />
        <img
          src="https://img.icons8.com/color/48/000000/flutter.png"
            alt="flutter"
        />
        <img
          src="https://img.icons8.com/color/48/000000/figma.png"
            alt="figma"
        />
      </Marquee>
    </div>
  );
}
