import Marquee from "react-fast-marquee";
import "./Tech.scss";

export default function Tech() {
  return (
    <div className="tech">
        <h3 className="sub-heading">Tools & Technologies</h3>
      <Marquee>
      <img
          src="https://img.icons8.com/color/48/000000/java.png"
          alt="python"
        />
        <img
          src="https://img.icons8.com/color/48/000000/my-sql.png"
          alt="python"
        />
        <img
          src="https://img.icons8.com/color/48/000000/php.png"
          alt="python"
        />
        <img
          src="https://img.icons8.com/color/48/000000/python--v1.png"
          alt="python"
        />
        <img
          src="https://img.icons8.com/color/48/000000/javascript--v1.png"
          alt="javascript"
        />
        <img
          src="https://img.icons8.com/color/48/000000/typescript.png"
          alt="typescript"
        />
        <img
          src="https://img.icons8.com/color/48/000000/react-native.png"
          alt="react"
        />
        <img
          src="https://img.icons8.com/color/48/000000/redux.png"
          alt="redux"
        />
        <img
          src="https://img.icons8.com/color/48/000000/nodejs.png"
          alt="nodejs"
        />
        <img
          src="https://img.icons8.com/color/48/000000/mongodb.png"
          alt="mongodb"
        />
        <img
          src="https://img.icons8.com/color/48/000000/express-js.png"
          alt="postgresql"
        />
        <img
          src="https://img.icons8.com/color/48/000000/docker.png"
          alt="docker"
        />
        <img
          src="https://img.icons8.com/color/48/000000/linux.png"
          alt="kubernetes"
        />
        <img
          src="https://img.icons8.com/color/48/000000/amazon-web-services.png"
          alt="aws"
        />
        <img
          src="https://img.icons8.com/color/48/000000/bash.png"
          alt="aws"
        />
        <img
          src="https://img.icons8.com/color/48/000000/c-programming.png"
          alt="azure"
        />
        <img
          src="https://img.icons8.com/color/48/000000/c-sharp-logo.png"
          alt="gcp"
        />
        <img
          src="https://img.icons8.com/color/48/000000/git.png"
          alt="git"
        />
        <img
          src="https://img.icons8.com/color/48/000000/arduino.png"
          alt="jenkins"
        />
        <img
          src="https://img.icons8.com/color/48/000000/firebase.png"
          alt="jenkins"
        />
        <img
          src="https://img.icons8.com/color/48/000000/sass.png"
            alt="vscode"
        />
        <img
          src="https://img.icons8.com/color/48/000000/flutter.png"
            alt="vscode"
        />
      </Marquee>
    </div>
  );
}
